{
 "title": "Mining dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "address",
    "label": "Address",
    "query": {
     "query": "label_values(mining_pool_worker_hashrate, address)"
    }
   },
   {
    "name": "worker_name",
    "label": "Worker",
    "query": {
     "query": "label_values(mining_pool_worker_hashrate, worker)"
    }
   },
   {
    "name": "pool",
    "label": "Pool",
    "query": {
     "query": "label_values(mining_pool_paid_total, pool)"
    }
   },
   {
    "name": "coin",
    "label": "Coin",
    "query": {
     "query": "label_values(mining_pool_balance, coin)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Paid total",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mining_pool_paid_total{pool=~\"$pool\", address=~\"$address\"}",
     "legendFormat": "{{pool}}/{{address}}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "mining_pool_balance{address=~\"$address\", pool=~\"$pool\"}",
     "legendFormat": "{{pool}}/{{address}}"
    }
   ]
  },
  {
   "title": "Last payout/24h reward",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "mining_pool_24hreward{pool=~\"$pool\", address=~\"$address\", coin=~\"$coin\"}",
     "legendFormat": "{{coin}} / {{pool}} / {{address}}"
    }
   ]
  },
  {
   "title": "Workers timeline",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "mining_pool_worker_online{pool=~\"$pool\", address=~\"$address\", coin=~\"$coin\", worker=~\"$worker_name\"}",
     "legendFormat": "{{pool}} / {{worker}}"
    }
   ]
  },
  {
   "title": "Worker Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "mining_pool_worker_hashrate{pool=~\"$pool\", address=~\"$address\", coin=~\"$coin\"}",
     "legendFormat": "{{pool}} / {{worker}}"
    }
   ]
  },
  {
   "title": "Hashrate AVG",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "mining_pool_worker_hashrate_avg{pool=~\"$pool\", address=~\"$address\", coin=~\"$coin\", worker=~\"$worker_name\"}",
     "legendFormat": "{{pool}} / {{worker}}"
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "targets": [
    {
     "expr": "mining_pool_hashrate{pool=~\"$pool\", address=~\"$address\", coin=~\"$coin\"}",
     "legendFormat": "{{pool}} / {{coin}} / {{address}}"
    }
   ]
  },
  {
   "title": "Stale shares %",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "mining_pool_worker_shares_stale_p{pool=~\"$pool\", worker=~\"$worker_name\"}",
     "legendFormat": "Stale: {{pool}} / {{worker}}"
    }
   ]
  }
 ]
}